In [1]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.metrics import silhouette_score
from scipy.spatial.distance import cdist

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('/home/natasha/Documents/Iprocure/Clustering-for-Product-Matching/data/unmatched_stockist_transactions.csv')
data.head()

,product_name,best_product_match,product_match_score,manufacturer_name,best_manufacturer_match,manufacturer_match_score
0,laibuta foliar feeds,murphy foliar feed,0.68,laib,eabl,0.22
1,White Candles - Riva,white line - mint & coriander,0.49,Halar Industries Ltd,zaam industries ltd.,0.83
2,Ampiclo-dawa dry syrup,vitastar pet syrup,0.40,.,mea ltd.,0.20
3,carvedilol(vidol)6.25mg,clopidol,0.45,Cosmos ltd,cosmos ltd.,0.91
4,Amoxil 'O'125mg,mineral 1-5725,0.41,GSK,wellstock,0.31

In [5]:
data = data.applymap(lambda x: x.lower() if isinstance(x, str) else x)
data['product_name'] = data['product_name'].apply(lambda x: x.strip() if isinstance(x, str) else x)
data.head()

,product_name,best_product_match,product_match_score,manufacturer_name,best_manufacturer_match,manufacturer_match_score
0,laibuta foliar feeds,murphy foliar feed,0.68,laib,eabl,0.22
1,white candles - riva,white line - mint & coriander,0.49,halar industries ltd,zaam industries ltd.,0.83
2,ampiclo-dawa dry syrup,vitastar pet syrup,0.40,.,mea ltd.,0.20
3,carvedilol(vidol)6.25mg,clopidol,0.45,cosmos ltd,cosmos ltd.,0.91
4,amoxil 'o'125mg,mineral 1-5725,0.41,gsk,wellstock,0.31

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8614931 entries, 0 to 8614930
Data columns (total 6 columns):
 #   Column                    Dtype
---  ------                    -----
 0   product_name              object
 1   best_product_match        object
 2   product_match_score       float64
 3   manufacturer_name         object
 4   best_manufacturer_match   object
 5   manufacturer_match_score  float64
dtypes: float64(2), object(4)
memory usage: 394.4+ MB

In [4]:
product_df = data[['product_name', 'manufacturer_name']]
product_df.drop_duplicates(subset=['product_name'], keep=first, inplace=True)
product_df.reset_index(drop=True, inplace=True)
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151852 entries, 0 to 151851
Data columns (total 2 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   product_name       151851 non-null  object
 1   manufacturer_name  150291 non-null  object
dtypes: object(2)
memory usage: 2.3+ MB